# Generated by Django 6.0.1 on 2026-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_turf_rejection_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('turf', 'date', 'start_time')},
        ),
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='status',
        ),
    ]
