# Generated by Django 6.0.1 on 2026-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0006_alter_slot_unique_together_slot_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
