# Generated by Django 6.0.1 on 2026-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0007_slot_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='hold_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=20),
        ),
    ]
