# Generated by Django 6.0.1 on 2026-02-24 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0008_slot_hold_expiry_slot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_bookings', to=settings.AUTH_USER_MODEL)),
                ('slots', models.ManyToManyField(related_name='turf_bookings', to='turfs.slot')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_bookings', to='turfs.turf')),
            ],
        ),
    ]
